### ISSUE TITLE
Mounting to a wrong URL because of CLI options order

### ISSUE THREAD

**Issue by jonohayon** [BHSSFRC/potential-engine#1]
When I ran the script with the following CLI args (in this specific order): `--address 0.0.0.0 --port 1181 --url /stream --use_omx`, the URL the stream was attached to wasn't the one I provided but what seems to be the names and emails of the authors of something: 
![Screen Shot 2019-10-09 at 20 46 56](https://user-images.githubusercontent.com/6596589/66507150-55cedf80-ead7-11e9-9285-d1a8f1c7e800.png)

When I changed the order of the arguments to have the `--url` option last the script performed as expected.

**Comment by c-x-berger** [comment]
Those are the contributors to GStreamer who appear in a bunch of header files. So that's at least a clue as to where those names are from... but I have no idea why they'd be getting put in the output like that.

I can't reproduce this on my x86 desktop, but I'll try again on a real Pi next.

For what it's worth, none of those options are actually doing anything except `--use_omx`. The others are all at default values. I *seriously* doubt that's causing the problem, but given that this is arguments being wack it's worth mentioning.

**Comment by c-x-berger** [comment]
I think - _think_ - this is a weird bug in the Raspbian version of GLib? It wouldn't be the first time that it's been wack on Raspbian and fine on my desktop.

On my Pi, using your arguments mounts to `/`. I'm going to see what I can get out of some admittedly blind tweaking, but I bet this is another time we can blame old packages having weird bugs.

**Comment by c-x-berger** [comment]
Fixed, getting a modern C++ argument parser is on the TODO list.
